running:
  env: 'new1'
  # 14 25   22 30 31  1  6  9
  all_seqs: ['2', '3', '4', '5', '7', '8', '10', '11', '12', '13', '15', '16', '17', '18', '19','20', '23', '24', '26', '27', '28', '29', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42']
  test_seqs: ['33', '34', '35', '36', '37', '38', '39', '40', '41', '42']
  sample: [0.3 ,0.5, 0.8]
  noise: [0.001, 0.005, 0.03 ]
  pc_folder: "./pre_data/pc_normal"
  desc_folder: "./pre_data/desc"
  gt_folder: "./pre_data/cls_gt"
  save_folder: "./result/thin_walled"
  learning_rate: 0.02
  weight_decay: 1.0e-6
  eval_ratio: 0.3
  neg_ratio: 1
  batch_size: 1024
